sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: oJpSrfUvnr+nQZy5aLj0tqex4PqBX2S+nDvvuhYHejxZmJaLA1TEifa+z9wq/oqjYlIN31y4RUI4o9Ur+CXIocY1d693Gj4OeY61SRc8fGXsy/xUGMWLlqYairMK7c2riWbS50yog8doMXz/tMUk6oNBvy9gpEPiyuZvToG3TJOp0dFu0YssAMGcm3SyVZAuOJCXa3Yz4vnleJ+VXaUY0xYRDWrMks0lEYqyXwD3RZ66oCAFc0+pwoTwzTxvKzirUplQwk5qPipT+4uqMG6E3injuqbf9ydozyjZYFDM9Eqy2ISZPDgFlufX7bG6pe5j/T/nqOjDH90gbh2a02iBP3utSP+P0nP6uAClMPA5cu1bRFF63If+uWkb+CqMoIaI940EHokI0jxfhOGu0o5vki91MJWWTEpHuv8g/Txf85VBYicVhEJe+7ITcwhImnkwmjAJlm+KaxEuSQchEmBLZ16IbK+oR70JJG2gYo6ZA7jLGYnXHGwRWrsfBcMdHVtgqHoi8xlbAEF71LZl+at9B0RttqkFykXSININe6uJwMkq9icGgdwfeZ/xNHRFqRxXAsag/2VjmrhayP4QbnfO219ZyVGilpqYBK6Isw0Qdp6NZHYCCvbeF8rbL3DK66c3hTzGZVk8842ytsXu+ZverkVMRxfy15sO68BcjsC1MlQ=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Told-in-the-East_5315
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy